version: '3.1'

services:

  db:
    image: mariadb
    env_file:
      - .env
    container_name: vite_mon_vol
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASS}
    ports:
      - "33061:3306"
