CREATE TABLE IF NOT EXISTS `users` (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
   `username` VARCHAR(255) NOT NULL,
   `email` VARCHAR(255) NOT NULL,
   `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
   `updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
   `password` VARCHAR(255) NOT NULL,
   `role` VARCHAR(16) DEFAULT 'customer'
);

CREATE TABLE IF NOT EXISTS `tours` (
    id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `name` VARCHAR(255) NOT NULL,
    `description` LONGTEXT,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
    `updated_at` DATETIME ON UPDATE CURRENT_TIMESTAMP,
    `destinations` LONGTEXT
);

CREATE TABLE IF NOT EXISTS `users_tours` (
   id INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `user_id` INT(10) UNSIGNED NOT NULL,
    `tour_id` INT(10) UNSIGNED NOT NULL,
   CONSTRAINT fk_user FOREIGN KEY (`user_id`) REFERENCES users(`id`),
   CONSTRAINT fk_tour FOREIGN KEY (`tour_id`) REFERENCES tours(`id`)
);